apiVersion: v1
kind: Service
metadata: 
  name: angular
  labels:
    app: angular
spec:
  type: NodePort
  selector: 
    app: angular
  ports:
   - protocol: TCP
     nodePort: 30002
     port: 4200
