apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular
  labels:
    app: angular
spec:
  selector:
    matchLabels:
      app: angular
  template:
    metadata:
      labels:
        app: angular
    spec:
      containers:
      - name: angular
        image: danieladiazp/test_angular:1.0
        ports:
        - containerPort: 4200
        env:
        - name: PORT
          value: '30201'
        - name: API
          value: laravel
