apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular
  labels:
    app: angular
spec:
  selector:
    matchLabels:
      app: angular
  template:
    metadata:
      labels:
        app: angular
    spec:
      containers:
      - name: angular
        image: PROYECTO/NOMBRE_IMAGEN:TAG
        ports:
        - containerPort: 4200
        env:
        - name: API
          valueFrom:
            configMapKeyRef:
              name: angular-config
              key: API
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: angular-config
              key: PORT
