apiVersion: v1
kind: Service
metadata: 
  name: laravel
  labels:
    app: laravel
spec:
  type: NodePort
  selector: 
    app: laravel
  ports:
    - protocol: TCP
      nodePort: 30001
      port: 8000
